### ISSUE TITLE
Chopper: Make it more intuitive which fields are required

### ISSUE THREAD

**Issue by DominicOram** [ess-dmsc/nexus-constructor#585]
As a user I would like it to more intuitive how to add an NXdisk_chopper that is correctly rendered. To render the chopper there are a number of required fields and currently the GUI gives you no indication of what these are or any feedback if you have entered them wrong.

**Comment by matthew-d-jones** [comment]
This problem is not specific to "which fields are required to render a chopper?". Another common scenario would be "what fields does Mantid require to be able to do something useful with this component?". This is exactly the type of situation that [NeXus Features](https://github.com/nexusformat/features) are designed to help with. 
In tackling this ticket we should consider whether the solution can scale beyond the case of choppers, and perhaps whether we can make use of NeXus features to automatically tag which fields are required for a particular feature.
