### ISSUE TITLE
Display axes in 3D view

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#69]
For example, as seen in the bottom-left corner of this [screenshot from Blender](https://windows-cdn.softpedia.com/screenshots/Blender_1.png)

**Comment by ACLay** [comment]
The work I did trying to make this is on branch `69_axis_indicator`.

When looking into rendering x,y,z planes, I found the following example that would also render axis indicators: https://github.com/KDAB/qt3d-examples/blob/b719644246f00c3a9abd42f132438c67b6f1eed2/cubespheretextures/src/qml/AxesGnomon.qml

That example would likely give a better graphical result than mine, as it uses the `GeometryRenderer.LineLoop` setting, to just draw single width lines instead of solid cylinders that can get wider along their length. A similar method to the one used in that example would make for a good way to render wireframe pane indicators.
